COmpleted By suman Shrestha(2408389)


 worksheet 01 (A coding exercises on Numpy)

To - Do - Task

Problem - 1: Array Creation:

1.	Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
empty_array = np.zeros((2,2))
print(empty_array)

[[0. 0.]
 [0. 0.]]


2.	Initialize an all one array with size 4X2.

In [ ]:
import numpy as np
one_array = np.ones((4,2))
print(one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3.	Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np
fill_array = np.full((4,3), (5))
print(fill_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


4.	Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np
fill_array = np.array([[1,2,3,4,5],[6,7,8,9,0]])
zeros_array = np.zeros_like(fill_array)
print(zeros_array)

[[0 0 0 0 0]
 [0 0 0 0 0]]


5.	Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np
fill_array = np.array([[1,2,3,4,5],[6,7,8,9,0],[1,2,3,4,5]])
ones_array = np.ones_like(fill_array)
print(ones_array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


6.
For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()
}

In [ ]:
import numpy as np
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1.	Create an array with values ranging from 10 to 49. {Hint:np.arange()}.

In [ ]:
import numpy as np
ranging_array = np.arange(10,50)
print(ranging_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2.	Create a 3X3 matrix with values ranging from 0 to 8.

In [ ]:
import numpy as np

print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3.	Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4.	Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}


In [ ]:
import numpy as np
print(np.random.random(30))
print(np.random.random(30).mean())


[0.03802327 0.7475448  0.933564   0.22905141 0.31286835 0.6728481
 0.62781273 0.96425796 0.94930801 0.00256014 0.93335027 0.30719972
 0.63287991 0.49050623 0.69415938 0.11685615 0.14716219 0.85577888
 0.58516604 0.40805208 0.46910968 0.28275862 0.16779971 0.05346977
 0.23251087 0.67622956 0.30290888 0.41271877 0.75008695 0.23265335]
0.5471382950000638


5.	Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
print(np.random.random(100).reshape(10,10))
print("minimum value is: ",np.random.random(100).reshape(10,10).min())
print("maximum value is: ",np.random.random(100).reshape(10,10).max())

[[0.0963473  0.59161992 0.88234369 0.26171988 0.56873106 0.83433028
  0.31990577 0.21556463 0.76788234 0.65846809]
 [0.20903463 0.44254932 0.53506919 0.79169372 0.21612318 0.63909078
  0.97949018 0.60451637 0.56191111 0.26161112]
 [0.79457806 0.24236304 0.9313075  0.24567167 0.27134878 0.92027457
  0.31353029 0.20007351 0.72893831 0.1875994 ]
 [0.14977007 0.52405098 0.50653646 0.19112591 0.19118804 0.30085401
  0.91860204 0.30035404 0.37738503 0.08180155]
 [0.22118256 0.99166395 0.79076071 0.50089997 0.90823347 0.22331751
  0.31876643 0.67042737 0.42153017 0.46074185]
 [0.44291683 0.11783868 0.01751238 0.18780441 0.61299383 0.00511637
  0.95237358 0.85362321 0.20465567 0.18347993]
 [0.76165843 0.16909087 0.46753878 0.53320276 0.50177572 0.79948443
  0.90389285 0.49721592 0.7607219  0.02127867]
 [0.77512833 0.83239365 0.48621423 0.13743977 0.1280101  0.22751579
  0.84246982 0.17581073 0.08023384 0.14981294]
 [0.31934109 0.43853218 0.10963469 0.63212541 0.97798131 0.47420119
  0.51954396

6.	Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.	Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
print(np.flip(arr))

[0 4 0 0 2 1]


8.	Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9.	Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
arr = np.ones((8,8))
arr[0::2,::2]=0
arr[1::2,1::2]=0
print(arr)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:


1.	Add the two array.


In [ ]:
import numpy as np
x= np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("addition of x and y array\n",x+y)
print("addition of v and w array",v+w)



addition of x and y array
 [[ 6  8]
 [10 13]]
addition of v and w array [20 22]


2.	Subtract the two array

In [ ]:
import numpy as np
x= np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("subtraction of x and y array:\n ",x-y)
print("subtraction of v and w array:",v-w)

subtraction of x and y array:
  [[-4 -4]
 [-4 -3]]
subtraction of v and w array: [-2 -2]


3.	Multiply the array with any integers of your choice.

In [ ]:
import numpy as np
x= np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("multiplication of x by 2 array:\n ",x*2)
print("multiplication of y by 3 array:\n ",y*3)
print("multiplication of v by 4 array:",v*4)
print("multiplication of w by 5 array:",w*5)

multiplication of x by 2 array:
  [[ 2  4]
 [ 6 10]]
multiplication of y by 3 array:
  [[15 18]
 [21 24]]
multiplication of v by 4 array: [36 40]
multiplication of w by 5 array: [55 60]


4.	Find the square of each element of the array.

In [ ]:
import numpy as np
x= np.array([[1,2],[3,5]])
y= np.array([[5,6],[7,8]])
v= np.array([9,10])
w= np.array([11,12])
print("square of the array x is \n ",x**2)
print("square of the array y is\n",y**2)
print("square of the array v is ",v**2)
print("square of the array w is ",w**2)

square of the array x is 
  [[ 1  4]
 [ 9 25]]
square of the array y is
 [[25 36]
 [49 64]]
square of the array v is  [ 81 100]
square of the array w is  [121 144]


5.	Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w= np.array([11,12])
print("dot product between: v(and)w ", np.dot(v,w))
print("dot product between: x(and)v ", np.dot(x,v))
print("dot product between: x(and)y ", np.dot(x,y))

dot product between: v(and)w  219
dot product between: x(and)v  [29 77]
dot product between: x(and)y  [[19 22]
 [50 58]]


6.	Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w= np.array([11,12])
print("Concatenate x(and)y along row:\n ",np.concatenate((x,y),axis=1))
print("Concatenate v(and)w along column: ",np.concatenate((v,w),axis=0))

Concatenate x(and)y along row:
  [[1 2 5 6]
 [3 5 7 8]]
Concatenate v(and)w along column:  [ 9 10 11 12]


7.	Concatenate x(and)v; if you get an error, observe and explain why did you get the error?



In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
print(np.concatenate((x,v),axis=0))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

  ==>  To concatenate the two array it should be in same dimentional array. And 1D array will only concatenate with verticallt i.e axis = 0


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]); Prove following with Numpy:


1.	Prove A.A−1 = I.


In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
print(np.linalg.inv(A))
print("Prove of A.A−1 = I \n",np.dot(A,np.linalg.inv(A)))

[[-2.    1.  ]
 [ 1.75 -0.75]]
Prove of A.A−1 = I 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2.	Prove AB ̸= BA.


In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB = np.dot(A,B)
BA = np.dot(B,A)
print("value of AB is=\n ",AB ,"\nvalue of BA is =\n ",BA)
if (AB==BA).all():
  print("AB = BA")
else:
    print("\nAB != BA")

value of AB is=
  [[23 13]
 [51 29]] 
value of BA is =
  [[36 44]
 [13 16]]

AB != BA


3.	Prove (AB)T = BTAT.

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB = np.dot(A,B)
BT = np.transpose(B)
AT = np.transpose(A)
ABT = np.transpose(AB)
BTAT = np.dot(BT,AT)
print("value of transpose AB is=\n ",ABT ,"\nvalue of transpose B dot transpose A is =\n ",BTAT)
if (ABT==BTAT).all():
  print("ABT = BTAT")
else:
    print("\nABT != BTAT")



value of transpose AB is=
  [[23 51]
 [13 29]] 
value of transpose B dot transpose A is =
  [[23 51]
 [13 29]]
ABT = BTAT


•	Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

 x − y + 2z = −3

 3x + y − z = 9

 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}




In [ ]:
import numpy as np
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([-1,-3,9])
# now taking inverse of A
A_inverse = np.linalg.inv(A)
print("inverse of A = ",A_inverse)
# now solving for X
x = np.dot(A_inverse,B)
print(x)
print(f"Solution: x = {x[0]} y = {x[1]} z = {x[2]}")

inverse of A =  [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
[ 2.  1. -2.]
Solution: x = 2.0 y = 1.0 z = -2.0


**4.2	Experiment: How Fast is Numpy?**


In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:

**.** Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure and Print the time taken for this operation.


In [ ]:
import numpy as np
import random
from timeit import timeit
z1_list = random.sample(range(10000000+1),1000000)
z2_list = random.sample(range(10000000+1),1000000)
def add(z1,z2):
  return [z1+z2 for z1,z2 in zip(z1,z2)]
time = timeit("add(z1_list,z2_list)",globals=globals(),number = 1000)
print(time)


172.97663174099944


•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import numpy as np
import random
from timeit import timeit
z1 = np.array(random.sample(range(10000000+1),1000000))
z2 = np.array(random.sample(range(10000000+1),1000000))
def add(z1,z2):
  return np.add(z1,z2)
time = timeit("add(z1,z2)",globals=globals(),number = 1000)
print(time)

1.2814406929992401


2. Element-wise Multiplication


•	Using Python Lists, perform element-wise
 multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.


In [ ]:
import numpy as np
import random
from timeit import timeit
z1_list = random.sample(range(10000000+1),1000000)
z2_list = random.sample(range(10000000+1),1000000)
def mul(z1,z2):
  return [z1*z2 for z1,z2 in zip(z1,z2)]

time = timeit("mul(z1_list,z2_list)",globals=globals(),number = 1000)
print(time)

214.75644005100003


•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import numpy as np
import random
from timeit import timeit
z1 = np.array(random.sample(range(10000000+1),1000000))
z2 = np.array(random.sample(range(10000000+1),1000000))
def mul(z1,z2):
  return np.multiply(z1,z2)
time = timeit("mul(z1,z2)",globals=globals(),number = 1000)
print(time)

1.478543578999961


3. Dot Product


•	Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and Print the time taken for this operation.


In [ ]:
import numpy as np
import random
from timeit import timeit
z1_list = random.sample(range(10000000+1),1000000)
z2_list = random.sample(range(10000000+1),1000000)
def dot(z1,z2):
  return sum([z1*z2 for z1,z2 in zip(z1,z2)])
time = timeit("dot(z1_list,z2_list)",globals=globals(),number = 1000)
print(time)

295.8430008739997


•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import numpy as np
import random
from timeit import timeit
z1 = np.array(random.sample(range(10000000+1),1000000))
z2 = np.array(random.sample(range(10000000+1),1000000))
def dot(z1,z2):
  return np.dot(z1,z2)

time = timeit("dot(z1,z2)",globals=globals(),number = 1000)
print(time)

1.0460358190011902


4. Matrix Multiplication
•	Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.


In [ ]:
import random
from timeit import timeit

z1_list = [[random.randint(0, 1000000) for _ in range(1000)] for _ in range(1000)]
z2_list = [[random.randint(0, 1000000) for _ in range(1000)] for _ in range(1000)]

def mul(z1, z2):
  # Corrected the ranges to match the matrix dimensions (1000x1000)
  return [[sum(z1[i][k] * z2[k][j] for k in range(1000))
           for j in range(1000)]
           for i in range(1000)]

time = timeit("mul(z1_list, z2_list)", globals=globals(), number=1000)
print(time)

•	Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.


In [ ]:
import numpy as np
import random
from timeit import timeit
z1 = np.random.random(1000000).reshape(1000*1000)
z2 = np.random.random(1000000).reshape(1000*1000)
print(z1.shape)
print(z1)
print(z2.shape)
print(z2)
def matrixMultiplication(z1,z2):
  return np.multiply(z1,z2)
time = timeit("matrixMultiplication(z1,z2)",globals=globals(),number = 1000)
print(time)
print(matrixMultiplication(z1,z2))


(1000000,)
[0.6470263  0.15696194 0.27523208 ... 0.09294907 0.95794465 0.86900622]
(1000000,)
[0.54388692 0.79967276 0.30438251 ... 0.72676093 0.51829241 0.28487458]
1.7022024859998055
[0.35190914 0.12551818 0.08377583 ... 0.06755175 0.49649544 0.24755778]
